Feature/EPC-8 Cardholder select the payment method
jortiz3109/escuela-php-checkout pull request #4
Opened 2021-10-20 19:57 UTC by JuanZea

2021-10-26 21:46 UTC, jortiz3109 requested changes

2021-10-26 21:46 UTC, jortiz3109 commented on app/Http/Controllers/Api/v1/SessionController.php
> +    public function paymentMethods(Session $session): PaymentMethodCollection
¿Un controlador de sesiones si debería listar métodos de pago?

2021-10-26 21:46 UTC, jortiz3109 commented on app/Http/Controllers/SessionController.php
> +    public function payment(Session $session, Request $request)
¿Este método si debería llamrse payment?

2021-10-26 21:46 UTC, jortiz3109 commented on app/Http/Controllers/SessionController.php
> +    public function payment(Session $session, Request $request)
¿Donde está el tipo de dato de retorno?

2021-10-26 21:46 UTC, jortiz3109 commented on app/Http/Kernel.php
> +            \Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
¿Este middleware si es necesario?, creo que no

2021-10-26 21:46 UTC, jortiz3109 commented on app/Http/Resources/PaymentMethodCollection.php
> +    public function toArray($request)
¿Estos comentarios  si aportan valor?
¿Donde está el tipo de dato que se recibe?
¿Donde está el tipo de dato que se retorna?

2021-10-26 21:46 UTC, jortiz3109 commented on app/Http/Resources/PaymentMethodResource.php
> +    public function toArray($request)
¿Estos comentarios si aportan valor?
¿Donde está el tipo de dato que se recibe?
¿Donde está el tipo de dato que se retorna?

2021-10-26 21:46 UTC, jortiz3109 commented on app/Models/Merchant.php
> +    public function sessions()
¿tipo de dato de retorno?

2021-10-26 21:46 UTC, jortiz3109 commented on app/Models/Merchant.php
> +    public function paymentMethods()
¿Tipo de dato de retorno?

2021-10-26 21:46 UTC, jortiz3109 commented on app/Models/Session.php
> +    public function merchant()
¿Tipo de dato de retorno?

2021-10-26 21:46 UTC, jortiz3109 commented on app/Providers/AppServiceProvider.php
>      public function register()
¿Donde está el tipo de dato de retorno?

2021-10-26 21:46 UTC, jortiz3109 commented on database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php
> +    public function up()
¿Tipo de dato de retorno?

2021-10-26 21:46 UTC, jortiz3109 commented on database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php
> +            $table->string('name');
¿Longitud de este campo?

2021-10-26 21:46 UTC, jortiz3109 commented on database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php
> +            $table->text('abilities')->nullable();
¿Para que sirve abilities?

2021-10-26 21:46 UTC, jortiz3109 commented on database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php
> +    public function down()
¿Tipo de dato de retorno?
¿Este comentario si aporta valor?

2021-10-26 21:46 UTC, jortiz3109 commented on resources/components/ProgressBar.vue
> +            :class="{
¿Esto si debería ir acá?

2021-10-26 21:46 UTC, jortiz3109 commented on resources/components/TestRequest.vue
> +<template>
¿Que es un TestRequest y que hace acá?

2021-10-26 21:46 UTC, jortiz3109 commented on routes/api.php
> +Route::get('/v1/session/{session:uuid}/payment-methods', [SessionController::class, 'paymentMethods'])->name('session.paymentMethods');
¿Este nombre de ruta si está bien planteado?

2021-10-26 21:46 UTC, jortiz3109 commented on tests/Feature/Api/V1/Session/PaymentMethodTest.php
> +<?php
¿Y este controlador para que?

2021-10-27 02:41 UTC, JuanZea commented on app/Http/Controllers/Api/v1/SessionController.php
> +    public function paymentMethods(Session $session): PaymentMethodCollection
Cambiado a "PaymentMethodController"

2021-10-27 02:42 UTC, JuanZea commented on app/Http/Controllers/SessionController.php
> +    public function payment(Session $session, Request $request)
Controlador eliminado porque no hace parte de la tarea

2021-10-27 02:42 UTC, JuanZea commented on app/Http/Kernel.php
> +            \Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
Comentado nuevamente

2021-10-27 02:44 UTC, JuanZea commented on app/Http/Resources/PaymentMethodCollection.php
> +    public function toArray($request)
Comentarios que no aportan valor eliminados.
El tipo de dato genera una alerta en PhpStorm (No se por qué, debería agregarlo de todos modos?)
Tipo de dato de retorno agregado: "array"

2021-10-27 02:44 UTC, JuanZea commented on app/Http/Resources/PaymentMethodResource.php
> +    public function toArray($request)
Comentarios que no aportan valor eliminados.
El tipo de dato genera una alerta en PhpStorm (No se por qué, debería agregarlo de todos modos?)
Tipo de dato de retorno agregado: "array"

2021-10-27 02:45 UTC, JuanZea commented on resources/components/ProgressBar.vue
> +            :class="{
Componente eliminado porque no hace parte de la tarea

2021-10-27 02:45 UTC, JuanZea commented on resources/components/TestRequest.vue
> +<template>
Componente eliminado porque no hace parte de la tarea

2021-10-27 02:48 UTC, JuanZea commented on routes/api.php
> +Route::get('/v1/session/{session:uuid}/payment-methods', [SessionController::class, 'paymentMethods'])->name('session.paymentMethods');
Nombre de la ruta cambiado a: "api.v1.paymentMethods.discover", porque pertenece a el controlador **PaymentMethodController** y el método **descubre** los métodos de pago del comercio

2021-10-27 02:53 UTC, JuanZea commented on tests/Feature/Api/V1/Session/PaymentMethodTest.php
> +<?php
El controlador encargado de darle manejo a los **métodos de pago**, en este caso, con la funcionalidad de descubrir los métodos de pago de un comercio

2021-10-27 03:16 UTC, JuanZea commented on database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php
> +    public function up()
Archivo **AppServiceProvider** retornado a su estado inicial

2021-11-03 22:23 UTC, merged